parameters:
#    jsv_membres.example.class: JSV\MembresBundle\Example

services:
#    jsv_membres.example:
#        class: %jsv_membres.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
